/* Question bank derived from the 2026-2027 Oregon Driver Manual.
   Types: mc (multiple choice), tf (true/false), yn (yes/no),
          fib (fill in the blank), multi (choose all that apply),
          sign (identify the SVG sign).
   For mc/sign: a = index of correct option.
   For tf/yn:   a = true or false.
   For fib:     a = array of accepted answers (case-insensitive).
   For multi:   a = array of correct option indices. */
const CATEGORIES = {
  signs:   { name: "Signs & Traffic Signals", icon: "🚦" },
  rules:   { name: "Rules of the Road", icon: "🛣️" },
  speed:   { name: "Speed & the Basic Rule", icon: "⏱️" },
  parking: { name: "Parking, Stopping & School Zones", icon: "🅿️" },
  safe:    { name: "Safe & Defensive Driving", icon: "🛡️" },
  impaired:{ name: "Impaired & Distracted Driving", icon: "🚫" },
  license: { name: "Licensing, Insurance & Collisions", icon: "🪪" },
  sharing: { name: "Sharing the Road", icon: "🚲" }
};

const QUESTIONS = [
// ============ SIGNS & SIGNALS ============
{c:"signs",t:"sign",s:"stop",q:"What must you do at this sign?",
 o:["Slow down and proceed if clear","Come to a complete stop, yield, and stay stopped for pedestrians in crosswalks","Stop only if other traffic is present","Yield only to vehicles on your right"],a:1,
 e:"A stop sign (octagon) means come to a complete stop, yield to other vehicles, and stop and stay stopped for pedestrians crossing in marked or unmarked crosswalks."},
{c:"signs",t:"sign",s:"yield",q:"What does this sign mean?",
 o:["Merge ahead","Reduce speed and yield right of way; stop if needed","No entry","Divided highway ends"],a:1,
 e:"A yield sign (triangle) means reduce speed and yield right of way. If needed, stop the same as you would for a stop sign."},
{c:"signs",t:"sign",s:"doNotEnter",q:"You see this sign at a ramp. What does it mean?",
 o:["Road closed for construction","Do not enter — you would be going the wrong way","One-way road in your direction","No parking beyond this point"],a:1,
 e:"Do Not Enter warns you not to enter a road or freeway. You will see it if you are going the wrong way."},
{c:"signs",t:"sign",s:"noUTurn",q:"This sign tells you:",
 o:["No left turns","No U-turns","Roundabout ahead","Divided highway"],a:1,
 e:"A red circle with a slash prohibits the movement shown — here, U-turns."},
{c:"signs",t:"sign",s:"pedCrossing",q:"What should you do when you see this yellow diamond sign?",
 o:["Stop immediately","Be alert for people crossing your path","Pedestrians are prohibited here","School zone — slow to 20 mph"],a:1,
 e:"The pedestrian crossing warning sign means be alert for people crossing your path. It may include a flashing yellow beacon."},
{c:"signs",t:"sign",s:"schoolZone",q:"This five-sided sign means:",
 o:["Hospital zone","Playground ahead","School zone or school crossing — look for children and be ready to stop","Pedestrian mall"],a:2,
 e:"The pentagon (five-sided) sign marks the beginning of school zones and warns of school crossings."},
{c:"signs",t:"sign",s:"slipperyWet",q:"What does this sign mean?",
 o:["Winding road ahead","Slippery when wet","Obstacle in the road","Curves ahead"],a:1,
 e:"Manual sample question: this sign means the pavement is unusually slick when wet."},
{c:"signs",t:"sign",s:"railroad",q:"This round yellow sign with an X and RR means:",
 o:["Road crossing ahead","Railroad crossing ahead — you may have to stop","Rest area ahead","Intersection with a rural road"],a:1,
 e:"The railroad advance warning sign tells you a railroad crossing is ahead. Look, listen and slow down."},
{c:"signs",t:"sign",s:"laneEnds",q:"What does this sign tell drivers?",
 o:["Divided highway begins","The indicated lane ends soon — merge into the through lane","Two-way traffic ahead","Added lane, no merge needed"],a:1,
 e:"Lane Reduction: the indicated lane ends soon. Vehicles in that lane must merge into the through lane."},
{c:"signs",t:"sign",s:"twoWayTraffic",q:"This sign warns you that:",
 o:["Passing is prohibited","The one-way road joins a two-way road — you will face oncoming traffic","A divided highway begins","You must keep right"],a:1,
 e:"Two-Way Traffic Ahead: the one-way road joins a two-way road and you will be facing oncoming traffic."},
{c:"signs",t:"sign",s:"roundaboutAhead",q:"What is ahead when you see this sign?",
 o:["A traffic circle or roundabout","A cloverleaf freeway interchange","A U-turn area","A one-way loop road"],a:0,
 e:"A warning sign with arrows in a circle pattern indicates a circular intersection (roundabout) is ahead."},
{c:"signs",t:"sign",s:"stopAhead",q:"Why would this sign be posted?",
 o:["A stop sign ahead may be hidden or come up quickly — slow down and prepare to stop","Stop here for pedestrians","The intersection ahead is closed","Yield sign ahead"],a:0,
 e:"Stop Ahead warns there is a stop sign ahead. Slow down and prepare to stop."},
{c:"signs",t:"sign",s:"workZone",q:"Orange diamond signs like this one indicate:",
 o:["Warning of a school zone","Work zone conditions ahead","Recreation area","Hazardous materials route"],a:1,
 e:"Work zones are defined by orange traffic control devices. Orange signs warn you what to expect ahead."},
{c:"signs",t:"sign",s:"slowMoving",q:"You see this emblem on the back of a vehicle. It is a:",
 o:["Hazmat placard","Slow moving vehicle, such as farm equipment","Wide load marker","Student driver marker"],a:1,
 e:"The Slow Moving Vehicle emblem (reflective red border, fluorescent orange center) must be displayed by slow vehicles like farm equipment."},
{c:"signs",t:"sign",s:"guide",q:"Green signs like this one are used to:",
 o:["Warn of hazards","Give exit information and directions to roads or cities","Mark recreation areas","Regulate speed"],a:1,
 e:"Guide or information signs are green. They give exit information or show the direction of roads or cities."},
{c:"signs",t:"sign",s:"hospital",q:"Blue signs like this one tell you about:",
 o:["Regulations you must obey","Services or facilities along the highway, such as a hospital","Construction zones","Scenic viewpoints"],a:1,
 e:"Motorist service signs are blue — gas, food, lodging, rest areas, EV charging, accessibility, or the road to a hospital."},
{c:"signs",t:"sign",s:"recreation",q:"Brown road signs point to:",
 o:["Military bases","Historic, cultural, scenic and recreational locations","Truck routes","Farm equipment crossings"],a:1,
 e:"Brown signs point to historic and cultural locations, scenic areas, picnic grounds, and parks."},
{c:"signs",t:"sign",s:"centerTurnLane",q:"This sign marks a lane that is used for:",
 o:["Passing slower traffic","Left turns by traffic from both directions","Buses only","Emergency vehicles only"],a:1,
 e:"Center Lane Turn Only: the center lane is shared for left turns from both directions. It is illegal to travel in it."},
{c:"signs",t:"sign",s:"hov",q:"A lane with this sign is reserved for:",
 o:["Hybrid vehicles","Vehicles carrying at least the number of persons noted on the sign","Heavy trucks","Motorcycles only"],a:1,
 e:"High Occupancy Vehicle lanes are reserved for vehicles carrying at least two or more persons, as noted on the sign."},
{c:"signs",t:"sign",s:"noTurnOnRed",q:"At an intersection with this sign you must:",
 o:["Never turn at this intersection","Wait for a green signal before turning","Turn only after stopping","Turn only between 7 a.m. and 5 p.m."],a:1,
 e:"No Turn on Red: you may not turn during the red light. You must wait for the signal to turn green."},
{c:"signs",t:"sign",s:"schoolSpeed",q:"When a yellow light on this sign is flashing, it means:",
 o:["School is closed","Children are arriving at or leaving school — obey the 20 mph limit","The limit applies only to buses","Crossing guard on duty ahead"],a:1,
 e:"Any time a yellow light on a school speed sign is flashing, children are arriving at or leaving school and the 20 mph limit applies."},
{c:"signs",t:"sign",s:"transitOnly",q:"In a lane marked with this sign, you may:",
 o:["Drive continuously to avoid congestion","Briefly enter only to turn, park, or reach a driveway where permitted","Never enter under any circumstance","Drive only at night"],a:1,
 e:"Transit Only lanes are for transit vehicles (and bikes if indicated). Where permitted, you may briefly use the lane to turn, pull over to park, or enter a driveway — always yielding to transit and bicycles."},
{c:"signs",t:"mc",q:"Regulatory prohibitive signs are red and white. Which of these is a regulatory prohibitive sign?",
 o:["Do Not Enter","Railroad Advance","Hospital Ahead","Merge"],a:0,
 e:"Manual sample question: Do Not Enter is a red regulatory prohibitive sign. Railroad Advance is a warning; Hospital is a service sign."},
{c:"signs",t:"mc",q:"If a traffic signal is dark because of a power outage, you should:",
 o:["Wait for a police officer to direct traffic","Treat it like a yield sign","Treat it like there are stop signs in all directions","Proceed at normal speed with caution"],a:2,
 e:"Manual sample question: if a signal appears dark, stop as if there are stop signs in all directions."},
{c:"signs",t:"mc",q:"A flashing red traffic signal is treated the same as:",
 o:["A yield sign","A stop sign","A warning sign","A green light with caution"],a:1,
 e:"A flashing red or a dark signal is treated the same as a stop sign."},
{c:"signs",t:"mc",q:"A flashing yellow signal means:",
 o:["Stop and wait for green","Slow down and proceed with caution","Signal is about to turn red","Pedestrians only may proceed"],a:1,
 e:"A flashing yellow signal means slow down and proceed with caution."},
{c:"signs",t:"mc",q:"A steady yellow light warns you that:",
 o:["Pedestrians are crossing","The signal is about to turn red — stop unless you cannot do so safely","You may speed up to clear the intersection","Cross traffic has a green light"],a:1,
 e:"A steady yellow warns the signal is about to turn red. Stop before entering; if you cannot stop safely, drive carefully through."},
{c:"signs",t:"mc",q:"A flashing yellow arrow at a left-turn signal means:",
 o:["Left turns are prohibited","You may turn left after yielding to pedestrians and oncoming traffic","You have the protected right of way to turn","The signal is broken"],a:1,
 e:"A flashing yellow arrow means you may make the movement shown, but must first yield to pedestrians and oncoming traffic — oncoming traffic has a green."},
{c:"signs",t:"mc",q:"A steady green arrow means:",
 o:["Yield before turning","You have the right of way to make the movement indicated","Turn only if no signs prohibit it","Pedestrians may not cross"],a:1,
 e:"A steady green arrow means you have the right of way and may make the movement indicated by the arrow."},
{c:"signs",t:"tf",q:"True or False: At a red light, after stopping, you may turn right onto a two-way road unless a sign or police officer says otherwise.",a:true,
 e:"After a complete stop at a red signal, you may turn right onto a two-way road unless prohibited by a sign or officer."},
{c:"signs",t:"tf",q:"True or False: You may turn left on a red light when turning from a two-way road onto a two-way road.",a:false,
 e:"It is illegal to execute a left turn onto a two-way road against a red light. Left on red is only allowed when entering a one-way road in the direction of travel."},
{c:"signs",t:"yn",q:"You are at a red arrow after a complete stop, wanting to turn right onto a two-way street. No sign prohibits it. May you turn?",a:true,
 e:"The same turns allowed on a steady red signal are allowed for a red arrow — including right on red after stopping, unless a sign prohibits it."},
{c:"signs",t:"fib",q:"A stop sign has ____ sides.",a:["8","eight"],
 e:"A stop sign is an octagon — eight sides — so it can be recognized by shape alone."},
{c:"signs",t:"mc",q:"What color are warning signs that alert you to possible hazards or changing road conditions?",
 o:["Orange","Yellow","Green","Blue"],a:1,
 e:"Warning signs are yellow. Orange marks work zones; green is guide info; blue is motorist services."},
{c:"signs",t:"mc",q:"Safety corridors are stretches of highway with more fatal and serious crashes than average. What should you do there?",
 o:["Drive below the speed limit at all times","Turn on your headlights for safety","Use your hazard lights","Avoid using cruise control"],a:1,
 e:"In marked safety corridors, turn on your lights for safety. Signs may include diamond-shaped flags."},
{c:"signs",t:"multi",q:"Select ALL turns you are allowed to make at a red light after a complete stop (no prohibiting signs):",
 o:["Right turn onto a two-way road","Left turn onto a one-way road (in its direction) from a two-way road","Left turn onto a two-way road","Right turn onto a one-way road going right"],a:[0,1,3],
 e:"On red you may turn right onto a two-way road, and turn right or left onto a one-way road in the direction of its traffic. Left onto a two-way road is illegal on red."},
{c:"signs",t:"mc",q:"A dotted white line before a freeway exit ramp tells you:",
 o:["Passing is prohibited","The lane you are in will not continue on the same route (exit-only)","The shoulder begins","HOV lane begins"],a:1,
 e:"A dotted white line before an exit or intersection means your lane will not continue on the same route, such as an exit-only lane."},
{c:"signs",t:"mc",q:"A double solid white line between lanes means:",
 o:["Lane changes are not allowed — stay in your lane","Pass with caution","HOV lane boundary","Parking is prohibited"],a:0,
 e:"A double solid white line means you are not allowed to change lanes. Stay in your lane."},
{c:"signs",t:"mc",q:"A broken yellow line on your side of the center line means:",
 o:["Passing is not allowed on either side","Passing is allowed on both sides only","Passing is allowed on your side","The road becomes one-way"],a:2,
 e:"Manual sample question: a broken yellow line on your side means passing is allowed on your side."},
{c:"signs",t:"mc",q:"What do solid red pavement lanes indicate?",
 o:["Fire lanes","Transit Only lanes — not for cars","No parking zones","Emergency vehicle staging"],a:1,
 e:"Red markings designate Transit Only lanes for buses, light rail or bikes. Striped red lines show where you may briefly enter to turn, park or reach a driveway."},
{c:"signs",t:"mc",q:"A yield line painted on the pavement looks like:",
 o:["A solid white bar","A row of triangles pointing toward your vehicle","Diagonal yellow stripes","A double white line"],a:1,
 e:"A yield line is a row of triangles in your lane pointing toward your vehicle, marking where you must yield."},
{c:"signs",t:"tf",q:"True or False: You may make a left turn across a double solid yellow center line to enter a driveway after yielding to oncoming traffic.",a:true,
 e:"You may turn left across double solid yellow lines to enter or exit a roadway after waiting for oncoming traffic to clear. Passing across them is what's prohibited."},
{c:"signs",t:"tf",q:"True or False: It is legal to travel along a painted median that has double yellow lines on both sides.",a:false,
 e:"It is illegal to travel in a median with double yellow lines, and you may not use a painted median as a turn lane."},
{c:"signs",t:"mc",q:"Yellow diagonal stripes painted inside a median tell you:",
 o:["Passing area","Fixed objects ahead or areas where vehicles are not allowed — do not drive or turn across them","Turn lane for both directions","Bicycle crossing area"],a:1,
 e:"Yellow diagonal stripes warn of fixed objects or closed areas. It is illegal to drive in or turn across these stripes."},
{c:"signs",t:"mc",q:"A sharrow (two chevrons above a bicycle symbol painted on the road) means:",
 o:["Bikes must leave the road","The lane is shared and people riding bicycles may be in the road","A protected bike lane begins","Bicycles may not pass"],a:1,
 e:"A sharrow indicates a shared lane where people riding bicycles may be in the road."},
{c:"signs",t:"mc",q:"Variable speed limit signs (black and white digital 'SPEED LIMIT' signs):",
 o:["Are only advisory","Change the legal speed limit based on conditions and are enforceable","Apply only to trucks","Operate only at night"],a:1,
 e:"Variable speed limit signs change the speed limit based on traffic, weather or road conditions. Police may enforce them like any speed limit sign."},

// ============ RULES OF THE ROAD ============
{c:"rules",t:"mc",q:"When entering a freeway, you should:",
 o:["Slow down","Speed up and merge with traffic","Turn on your hazard lights to warn traffic","Stop and wait for a large gap"],a:1,
 e:"Manual sample question: use the on-ramp to speed up and merge with fast-moving traffic. You must still yield to traffic already on the freeway."},
{c:"rules",t:"mc",q:"When passing another vehicle on a two-lane road:",
 o:["It is okay to exceed the speed limit briefly","Do not begin your pass before the start of a passing zone","You may pass in an intersection if it looks clear","Honk before pulling out"],a:1,
 e:"Manual sample question: your pass may not begin before the start of a passing zone and must be completed before a no-passing zone. Never exceed the speed limit."},
{c:"rules",t:"mc",q:"When you stop behind another vehicle, you should be far enough back to see:",
 o:["Where its rear tires meet the road","The top of its bumper","Its brake lights","Its rearview mirror"],a:0,
 e:"Manual sample question: stop so you can see where the rear tires of the vehicle in front meet the road."},
{c:"rules",t:"mc",q:"When turning from one road to another, you should:",
 o:["Swing wide to make the turn easier","Move into the bicycle lane before the turn","Turn into the closest lane in the direction you want to go","Turn into whichever lane is empty"],a:2,
 e:"Manual sample question: turn from the nearest lane in your direction of travel into the nearest lane in the direction you want to go."},
{c:"rules",t:"mc",q:"When you reach a roundabout, you must:",
 o:["Yield to traffic inside and exiting, wait for a gap, and merge","Always stop before entering, then merge","Accelerate to merge into traffic","Enter and stop inside if needed"],a:0,
 e:"Manual sample question: before entering a roundabout you must yield to traffic inside as well as exiting the roundabout, then merge when there's a gap."},
{c:"rules",t:"mc",q:"You are stopped at a red light on a two-way road waiting to turn left onto a one-way road. You:",
 o:["Must wait until the light is green","Can only turn if a left-turn sign is posted","Can turn on red after stopping and yielding to traffic and pedestrians","May never turn left onto a one-way road"],a:2,
 e:"Manual sample question: a left turn from a two-way road onto a one-way road is allowed against a red light after stopping and yielding."},
{c:"rules",t:"fib",q:"If your vehicle is moving in traffic, you must signal at least ____ feet before a turn or lane change.",a:["100","100 feet","one hundred"],
 e:"Use your turn signal at least 100 feet before the turn or lane change."},
{c:"rules",t:"mc",q:"At an intersection with stop signs in all four directions, if two drivers stop at the same time:",
 o:["The driver on the left goes first","When in doubt, yield to the driver on your right","The larger vehicle goes first","The driver going straight always goes first"],a:1,
 e:"It is common courtesy for the first to stop to go first. When in doubt, yield to the driver on your right."},
{c:"rules",t:"mc",q:"At an uncontrolled intersection (no signs or signals), you must yield to:",
 o:["Any vehicle in the intersection or approaching from your right","Vehicles approaching from your left","The faster vehicle","No one — first come, first served"],a:0,
 e:"Yield the right of way to any vehicle in the intersection or approaching from your right."},
{c:"rules",t:"mc",q:"You are on a road that ends at a T intersection with no signs or signals. You must:",
 o:["Yield to drivers on the through road","Proceed — you have the right of way","Stop only if traffic is heavy","Flash your lights and proceed"],a:0,
 e:"The driver on the road that ends must yield to drivers on the through road."},
{c:"rules",t:"mc",q:"At intersections with two-way stop signs across from each other, the driver turning left should:",
 o:["Go first","Yield to approaching or oncoming traffic going straight","Wait for a gap of 10 seconds","Honk before turning"],a:1,
 e:"The driver turning left should yield the right of way to approaching or oncoming traffic going straight."},
{c:"rules",t:"yn",q:"You have a green light, but traffic is backed up and there is no room for your vehicle on the other side of the intersection. Should you enter?",a:false,
 e:"Even with a green light, do not enter an intersection unless there is room for your vehicle on the other side."},
{c:"rules",t:"mc",q:"Inside a roundabout with an emergency vehicle approaching, you should:",
 o:["Stop immediately where you are","Continue through, exit, then pull over to the right","Pull to the center island","Back out of the roundabout"],a:1,
 e:"Never stop inside a roundabout. Move through and exit, then pull to the right shoulder to let emergency vehicles pass."},
{c:"rules",t:"tf",q:"True or False: It is legal to pass or drive beside a large truck within a roundabout.",a:false,
 e:"Trucks may need to straddle both lanes; it is illegal to pass or drive beside a truck within the roundabout."},
{c:"rules",t:"mc",q:"When exiting a roundabout you should:",
 o:["Use your right turn signal","Use your left turn signal","Use your hazard lights","Not signal — it confuses other drivers"],a:0,
 e:"Indicate your plan to exit the roundabout using your right turn signal, and watch for pedestrians in the crosswalk."},
{c:"rules",t:"mc",q:"You may pass on the right when:",
 o:["The vehicle ahead is slow","The vehicle ahead is making or signaling a left turn and there is room to pass on pavement (not in a bike lane)","Traffic on the left is congested","On any road wide enough for two cars"],a:1,
 e:"Passing on the right is only allowed when the vehicle ahead is making/signaling a left turn (with sufficient paved space, not a bike lane), or on multi-lane roads when passing a vehicle in the left lane."},
{c:"rules",t:"multi",q:"Select ALL locations where you must NOT cross the center line to pass:",
 o:["On a hill or curve with a blocked view","Approaching, at, or in an intersection or railroad crossing","When the vehicle ahead is stopped at a crosswalk for a pedestrian","On a straight road with a broken yellow line on your side"],a:[0,1,2],
 e:"Do not pass on hills or curves with limited view, at intersections or railroad crossings, or when a vehicle is stopped at a crosswalk. A broken yellow line on your side allows passing."},
{c:"rules",t:"mc",q:"When another driver starts to pass you, you should:",
 o:["Speed up so they can finish faster","Stay to the right and adjust your speed to help them return safely","Flash your lights to signal when it's safe","Move to the shoulder"],a:1,
 e:"Stay right and help the driver pass safely. It is illegal to flash your signals at drivers to tell them when to pass."},
{c:"rules",t:"mc",q:"When is it legal to drive in a two-way special left turn lane?",
 o:["Whenever traffic is congested","Only just before making a left turn (or completing one)","To pass slower traffic","When entering a freeway"],a:1,
 e:"It is illegal to travel in a two-way left turn lane. Enter it just before you want to turn and wait there for traffic to clear."},
{c:"rules",t:"mc",q:"When making a left turn from a two-way road onto a two-way road, you should approach in the lane:",
 o:["Nearest the right curb","Just to the right of the center line","Farthest from the center line","Any available lane"],a:1,
 e:"Approach with your vehicle in the lane just to the right of the center line, yield to oncoming traffic, and turn just before the imaginary center point of the intersection."},
{c:"rules",t:"multi",q:"U-turns are prohibited at which of these locations? Select ALL that apply:",
 o:["Intersections controlled by a traffic signal (unless a sign permits)","Between intersections in a city","On or at a railroad crossing","Outside city limits where you can be seen for 1,200 feet in both directions"],a:[0,1,2],
 e:"U-turns are prohibited at signal-controlled intersections (unless permitted by sign), between intersections in a city, at railroad crossings, and anywhere visibility is under 500 ft (city) / 1,000 ft (outside city)."},
{c:"rules",t:"fib",q:"Outside city limits, you may not make a U-turn where your vehicle cannot be seen by traffic coming from either direction within ____ feet.",a:["1000","1,000","one thousand"],
 e:"Outside city limits the visibility requirement is 1,000 feet; within city limits it is 500 feet."},
{c:"rules",t:"mc",q:"If you miss your freeway exit, you should:",
 o:["Stop and back up carefully on the shoulder","Make a U-turn at the median crossover","Go to the next exit","Stop and wait for a gap to reverse"],a:2,
 e:"Never stop or back up on a freeway. If you miss your exit, go on to the next one."},
{c:"rules",t:"mc",q:"Ramp meters on freeway on-ramps:",
 o:["Allow one vehicle per lane to proceed on each green light","Are only suggestions","Meter trucks only","Require a stop even when dark"],a:0,
 e:"Only one vehicle can proceed each time the green comes on. When your light turns green, speed up to merge. Do not stop at a dark ramp meter."},
{c:"rules",t:"mc",q:"When leaving a freeway you should:",
 o:["Slow down before the exit ramp","Maintain your speed until you are off the freeway, then slow to the ramp's advisory speed","Signal after entering the ramp","Use the shoulder to decelerate"],a:1,
 e:"Signal well ahead, maintain speed until off the freeway, then slow to the posted advisory speed once on the exit ramp."},
{c:"rules",t:"mc",q:"If you have vehicle trouble on a freeway, you should:",
 o:["Stop in your lane and turn on hazard lights","Move to the right shoulder, turn on hazard lights, and stay in or near your vehicle away from traffic","Walk along the freeway for help","Wave down passing cars"],a:1,
 e:"Move to the right shoulder or emergency area, use hazard lights, and stay in or near your vehicle on the side away from traffic. Walking along a freeway is dangerous."},
{c:"rules",t:"mc",q:"If you start to enter a freeway the wrong way, you should:",
 o:["Complete the entry and exit at the next ramp","Immediately pull to the side of the ramp, stop, turn on hazards, and cautiously turn around or back off","Speed through against traffic to the nearest exit","Stop in the travel lane and wait for police"],a:1,
 e:"Immediately pull off to the side of the ramp and stop, turn on your hazard lights, then cautiously turn around or back off the ramp."},
{c:"rules",t:"mc",q:"Before changing lanes, you should signal, check your mirrors, and:",
 o:["Honk your horn","Glance over your shoulder in the direction of the move to check your blind spot","Slow down significantly","Turn on your hazard lights"],a:1,
 e:"Mirrors don't show blind spots. Glance over your left shoulder when moving left, right shoulder when moving right."},
{c:"rules",t:"fib",q:"When required to stop at a railroad crossing with no stop line, stop at least ____ feet from the nearest rail.",a:["15","15 feet","fifteen"],
 e:"Manual sample question: stop at least 15 feet from the nearest rail if there is no stop line."},
{c:"rules",t:"mc",q:"Your vehicle stalls on railroad tracks and you see a train coming. You should:",
 o:["Try to restart the engine","Get out, get away from the tracks, and move at a 45° angle toward the train","Push the vehicle off the tracks","Wave at the train to stop"],a:1,
 e:"Get out and away immediately. Move at a 45-degree angle from the tracks in the direction of the approaching train so you are not hit by debris."},
{c:"rules",t:"tf",q:"True or False: It is legal to drive around a railroad crossing gate that is being raised.",a:false,
 e:"It is against the law — and extremely dangerous — to drive around or under a crossing gate while it is down or being raised or lowered."},
{c:"rules",t:"multi",q:"You must stop before railroad tracks when... (select ALL that apply):",
 o:["Flashing red lights are activated","A stop sign is posted, even if no train is visible","A flagger signals you to stop","Every time you cross tracks, no matter what"],a:[0,1,2],
 e:"Stop when red lights flash, a train is clearly approaching, a stop sign is posted, or a flagger signals. Not every crossing requires a stop when clear and uncontrolled by stop signs."},
{c:"rules",t:"mc",q:"When following a school bus, hazmat vehicle, or other vehicle required to stop at railroad tracks, you should:",
 o:["Pass it before the tracks","Be prepared to stop behind it","Honk to remind the driver to keep moving","Follow closely so you both clear together"],a:1,
 e:"All school buses and hazmat vehicles must stop at railroad tracks. Be prepared to stop when following them."},
{c:"rules",t:"mc",q:"When passing a stopped streetcar or light rail train, you should:",
 o:["Maintain speed while passing","Stop and stay stopped until it moves","Watch for pedestrians and pass with caution","Never pass under any circumstances"],a:1,
 e:"Manual sample question: if a streetcar or train stops to pick up or drop off people, stay behind it until it moves again or the people are safely away."},
{c:"rules",t:"mc",q:"Vehicles in a funeral procession:",
 o:["Must obey all signals like everyone else","May enter intersections without stopping; other drivers must yield to the procession","Have no special privileges","May exceed the speed limit"],a:1,
 e:"Funeral processions may enter an intersection without stopping and other vehicles must yield. It is illegal to join or drive between procession vehicles."},
{c:"rules",t:"mc",q:"On a two-lane road with no center line, drivers traveling in opposite directions must:",
 o:["Each give at least half the road to oncoming traffic","Pull over and stop for each other","Yield to the heavier vehicle","Sound their horns when meeting"],a:0,
 e:"When a road has no center line and traffic moves in opposite directions, drivers must give at least half the road to oncoming traffic."},
{c:"rules",t:"mc",q:"Before entering a road from an alley, driveway, or parking lot not controlled by signs, you must:",
 o:["Yield only to vehicles","Stop, then yield to approaching vehicles and pedestrians","Honk and proceed","Merge without stopping if clear"],a:1,
 e:"Stop before you enter or cross a road from an alley, driveway or parking lot, and yield to approaching vehicles and pedestrians."},
{c:"rules",t:"yn",q:"May you use hand-and-arm signals instead of signal lights at night?",a:false,
 e:"Hand-and-arm signals are only for daylight when people and vehicles are clearly visible at 1,000 feet. Use signal lights at night or in poor visibility."},
{c:"rules",t:"mc",q:"The correct hand-and-arm signal for a right turn is:",
 o:["Arm straight out the window","Arm bent upward at the elbow","Arm bent downward at the elbow","Arm waving forward"],a:1,
 e:"Left arm bent upward signals a right turn; straight out signals a left turn; bent downward signals stop or slowing."},
{c:"rules",t:"mc",q:"Oregon law allows a passenger vehicle to tow at most:",
 o:["One trailer or vehicle","Two light trailers","Three if under 26,000 lbs total","Any number with proper hitches"],a:0,
 e:"You may tow a maximum of one boat, utility trailer, or other vehicle behind a passenger or recreational vehicle. Towing a second is not allowed."},
{c:"rules",t:"mc",q:"A work zone's posted temporary speed limit applies:",
 o:["Only when workers are present","At all times, even if workers are not visible","Only during daylight","Only when flaggers direct traffic"],a:1,
 e:"Manual sample question: the temporary speed posted in a work zone applies at all times, even if workers are not visible."},
{c:"rules",t:"fib",q:"Traffic fines are ____ in all work zones.",a:["doubled","double","2x","doubled in all work zones"],
 e:"Traffic fines are doubled in all work zones, and you are expected to yield to workers."},
{c:"rules",t:"mc",q:"An automated flagger device shows a red light with the arm down. You must:",
 o:["Proceed slowly","Stop and wait until the yellow light flashes and the arm is up","Treat it as a 4-way stop","Change lanes and continue"],a:1,
 e:"Stop when the red light is on and the arm is down. Proceed when the yellow light is flashing and the arm is up."},

// ============ SPEED & BASIC RULE ============
{c:"speed",t:"mc",q:"Oregon's basic rule law states that you must:",
 o:["Always drive at the posted speed limit","Drive at a speed reasonable and cautious for existing conditions","Keep up with the flow of traffic even over the limit","Drive 5 mph under the limit in rain"],a:1,
 e:"The basic rule requires a speed reasonable and cautious for conditions, at all times on all roads. It never allows exceeding the speed limit."},
{c:"speed",t:"yn",q:"Can you violate the basic rule even while driving below the posted speed limit?",a:true,
 e:"Yes — if your speed is unsafe for existing conditions (weather, visibility, traffic), you violate the basic rule even below the limit."},
{c:"speed",t:"fib",q:"Unless posted otherwise, the speed limit in a residential district is ____ mph.",a:["25","25 mph","twenty five","twenty-five"],
 e:"25 mph applies in residential districts, public parks, and on ocean shores where vehicles are permitted."},
{c:"speed",t:"fib",q:"Unless posted otherwise, the speed limit in a business district is ____ mph.",a:["20","20 mph","twenty"],
 e:"20 mph applies in any business district and within school speed zones."},
{c:"speed",t:"fib",q:"The statutory speed limit when driving in an alley or narrow residential area is ____ mph.",a:["15","15 mph","fifteen"],
 e:"15 mph applies in alleys and narrow residential areas."},
{c:"speed",t:"mc",q:"On roads and highways not meeting any other definition and not otherwise posted, the speed limit is:",
 o:["45 mph","50 mph","55 mph","65 mph"],a:2,
 e:"55 mph applies on all roads and highways not meeting any other definition, unless otherwise posted."},
{c:"speed",t:"mc",q:"A safe following distance under normal conditions is defined as:",
 o:["1 second","2–4 seconds","5–6 car lengths","10 feet per 10 mph"],a:1,
 e:"A safe following distance is 2–4 seconds. For speeds over 30 mph, use 4 seconds or more."},
{c:"speed",t:"mc",q:"For speeds greater than 30 mph, your following distance should be:",
 o:["2 seconds","3 seconds","4 seconds or more","At least 100 feet"],a:2,
 e:"For speeds greater than 30 mph, a safe following distance should be 4 seconds or more."},
{c:"speed",t:"mc",q:"At 60 mph, your total stopping distance (reaction plus braking) is about:",
 o:["100 feet","150 feet","The length of a football field or more","Half a city block"],a:2,
 e:"At 60 mph, the distance from recognizing a hazard to a full stop is greater than the length of a football field."},
{c:"speed",t:"multi",q:"In which situations should you INCREASE your following distance? Select ALL that apply:",
 o:["On wet or slippery roads","When following motorcycles or bicycles","When pulling a trailer or carrying a heavy load","When driving in light traffic on a sunny day"],a:[0,1,2],
 e:"Increase following distance on slippery roads, behind riders who may stop suddenly, with heavy loads/trailers, in bad weather, near work zones, and while learning to drive."},
{c:"speed",t:"mc",q:"If you drive slower than the normal flow of traffic, you must:",
 o:["Turn on hazard lights","Use the right lane or drive as close as possible to the right edge","Wave vehicles around you","Speed up to match traffic"],a:1,
 e:"Slow drivers must use the right lane or keep close to the right edge, except when preparing to turn left. Pull off at the first safe area if traffic stacks up behind you."},
{c:"speed",t:"tf",q:"True or False: Yellow 'Variable Advisory Speed' digital signs set an enforceable speed limit.",a:false,
 e:"Variable advisory speed signs recommend a speed for conditions. They are not speed limits, though police can enforce unsafe speed through the basic rule."},
{c:"speed",t:"tf",q:"True or False: Racing — any acceleration or speed contest — is illegal on any Oregon road.",a:true,
 e:"It is illegal to race on any road, including acceleration contests and speed-record attempts."},
{c:"speed",t:"mc",q:"A pedestrian hit by a vehicle traveling 42 mph has about what risk of death?",
 o:["10%","25%","50%","90%"],a:2,
 e:"Per the manual: 23 mph ≈ 10% risk, 42 mph ≈ 50%, 58 mph ≈ 90%. Speed dramatically affects pedestrian survival."},
{c:"speed",t:"mc",q:"The higher your speed, the:",
 o:["Shorter your stopping distance","Less time you have to spot hazards and react, and the longer it takes to stop","More control you have","Smaller your blind spots"],a:1,
 e:"Higher speed means less time to spot hazards, judge traffic, and react — and greater stopping distance."},

// ============ PARKING & SCHOOL ZONES ============
{c:"parking",t:"fib",q:"When parallel parking, you must be no more than ____ inches from the curb.",a:["12","12 inches","twelve"],
 e:"Manual sample question: park parallel to and no more than 12 inches from the curb."},
{c:"parking",t:"mc",q:"What is the safest way to re-enter traffic from a parked position?",
 o:["Yield to other traffic after you signal and check your blind spots and mirrors","Signal, check blind spots, and pull out — traffic will slow","Check mirrors and signal; other traffic must yield to you","Accelerate quickly into the first gap"],a:0,
 e:"Manual sample question: signal, check blind spots and mirrors, and yield to all other traffic before leaving a parked or stopped position."},
{c:"parking",t:"mc",q:"Parked downhill next to a curb, you should turn your front wheels:",
 o:["Toward the curb","Away from the curb","Straight ahead","Either way, brake is enough"],a:0,
 e:"Downhill: turn wheels toward the curb. Uphill with curb: toward the travel lane (away from curb). No curb: toward the edge of the road. Always set the parking brake."},
{c:"parking",t:"mc",q:"Parked uphill next to a curb, you should turn your front wheels:",
 o:["Toward the curb","Toward the travel lane (away from the curb)","Straight","Doesn't matter with an automatic"],a:1,
 e:"Uphill against a curb: turn wheels toward the travel lane so the car rolls into the curb if brakes fail."},
{c:"parking",t:"mc",q:"When parking on a hill with no curb, turn your wheels:",
 o:["Toward the edge of the road","Toward the center line","Straight","Sharply left"],a:0,
 e:"With no curb, turn your wheels toward the edge of the road so the vehicle rolls away from traffic if the brake fails."},
{c:"parking",t:"fib",q:"You may not park within ____ feet of a fire hydrant.",a:["10","10 feet","ten"],
 e:"Parking is prohibited within 10 feet of a fire hydrant."},
{c:"parking",t:"fib",q:"You may not park within ____ feet of a marked or unmarked crosswalk at an intersection.",a:["20","20 feet","twenty"],
 e:"Parking is prohibited within 20 feet of a crosswalk at an intersection."},
{c:"parking",t:"fib",q:"You may not park within ____ feet of the nearest rail of a railroad or light rail crossing.",a:["50","50 feet","fifty"],
 e:"Parking is prohibited within 50 feet of the nearest rail — and within 50 feet of a signal or sign if your vehicle hides it."},
{c:"parking",t:"multi",q:"Where is parking prohibited? Select ALL that apply:",
 o:["On a sidewalk, crosswalk, or bike lane","Within an intersection","On the road side of a parked vehicle (double parking)","On the shoulder in an emergency with room for traffic to pass"],a:[0,1,2],
 e:"All the first three are illegal. Emergency parking on the shoulder is allowed if passing traffic has room and your vehicle doesn't create a hazard."},
{c:"parking",t:"mc",q:"Fines for illegally parking in a space reserved for persons with disabilities begin at:",
 o:["$65","$115","$165","$500"],a:2,
 e:"Fines begin at $165 and go up to $1,000 — even for 'just a few minutes' without a valid permit."},
{c:"parking",t:"mc",q:"If your parked vehicle can't be seen from 200 feet in each direction after a breakdown, you must:",
 o:["Leave it and get help","Warn traffic with flags, flares, or signals placed at least 200 feet away in each direction","Turn on the dome light","Leave the engine running with lights on"],a:1,
 e:"Warn approaching traffic with flags, flares, signs, signals or flaggers placed at least 200 feet from your vehicle in each direction."},
{c:"parking",t:"mc",q:"Before leaving your vehicle unattended you should:",
 o:["Turn off the engine, remove the key, and set the brakes","Leave it in neutral","Leave hazard lights off to save battery","Leave the key inside for towing"],a:0,
 e:"Turn off the engine, remove the key, set the brakes — and turn on hazard lights if stopped where parking isn't normally allowed."},
{c:"parking",t:"mc",q:"A school speed zone limit of 20 mph on a '7 a.m. to 5 p.m.' sign applies:",
 o:["Every day of the year","On days school is in session between 7 a.m. and 5 p.m.","Only when the light flashes","Weekends only"],a:1,
 e:"School-hours signs apply 7 a.m.–5 p.m. on days school is in session. If unsure whether it's a school day, slow to 20 mph."},
{c:"parking",t:"multi",q:"'Children are present' (triggering the 20 mph school speed) means... select ALL that apply:",
 o:["Children waiting at a crosswalk","Children occupying or walking within a crosswalk","A traffic patrol member assisting children at a crosswalk","Children visible anywhere inside the school building"],a:[0,1,2],
 e:"Children are present when they wait at, occupy, or walk within a crosswalk, or when a traffic patrol member is present to assist them."},
{c:"parking",t:"mc",q:"A school bus stops with flashing red lights on a road with a painted median. You are approaching from the opposite direction. You must:",
 o:["Continue — painted medians separate the roads","Stop — a painted median or turn lane does not create two separate roads","Slow to 20 mph and pass","Honk and proceed with caution"],a:1,
 e:"Manual sample question: with only a painted median or turn lane, traffic in ALL lanes must stop for the flashing red lights."},
{c:"parking",t:"mc",q:"You must stop for a school bus with flashing red lights and remain stopped until:",
 o:["The bus moves","The driver turns off the flashing red lights","All children are seated","30 seconds have passed"],a:1,
 e:"Stop before reaching the bus and remain stopped until the driver turns off the flashing red lights."},
{c:"parking",t:"yn",q:"You are on a divided highway with an unpaved median strip; a school bus on the other side stops with red lights flashing. Must you stop?",a:false,
 e:"On a divided highway with roads separated by an unpaved median or barrier, only traffic on the same side as the bus must stop."},
{c:"parking",t:"mc",q:"Flashing amber lights on a school bus mean:",
 o:["The bus is disabled","The bus is about to stop to load or unload children — prepare to stop","You may pass immediately","Children are already crossing"],a:1,
 e:"Amber warns the bus is about to stop on the road to load or unload children. Prepare to stop; when red flashes, you must stop."},
{c:"parking",t:"tf",q:"True or False: Flashing amber and red lights on a worker or place-of-worship bus must be treated the same as a school bus.",a:true,
 e:"If such a bus turns on flashing amber or red lights, treat them exactly the same as a school bus."},
{c:"parking",t:"mc",q:"A public transit bus signals to re-enter traffic and shows a flashing 'YIELD' sign on its back. Vehicles approaching from the rear must:",
 o:["Pass quickly on the left","Yield to the bus","Honk to warn the bus","Stop completely"],a:1,
 e:"Vehicles approaching from the rear must yield when a bus driver signals to re-enter the traffic lane with the flashing yield sign."},

// ============ SAFE & DEFENSIVE DRIVING ============
{c:"safe",t:"mc",q:"A driver has three tools to avoid a collision:",
 o:["Slow down, check mirrors, stop","Stop quickly, turn quickly, speed up","Honk, brake, swerve","Flash lights, brake, pull over"],a:1,
 e:"Manual sample question: the three collision-avoidance tools are stopping quickly, turning quickly, and speeding up."},
{c:"safe",t:"mc",q:"It is illegal to have fog lights on when:",
 o:["You are required to dim your headlights","Using them to see through fog","Driving under 35 mph","It is raining"],a:0,
 e:"Manual sample question: when required to dim your headlights, auxiliary lights such as fog lights must be off."},
{c:"safe",t:"fib",q:"You must dim your high beams when an oncoming vehicle is within ____ feet.",a:["500","500 feet","five hundred"],
 e:"Dim high beams within 500 feet of oncoming vehicles, and within 350 feet when following another vehicle."},
{c:"safe",t:"fib",q:"You must dim your high beams when following another vehicle within ____ feet.",a:["350","350 feet","three hundred fifty"],
 e:"Dim when following within 350 feet — headlight glare in a mirror can blind the driver ahead."},
{c:"safe",t:"mc",q:"Headlights must be turned on:",
 o:["Only when it rains","From sunset to sunrise, and any time you can't see people or vehicles 1,000 feet ahead","Only on freeways at night","Whenever wipers are off"],a:1,
 e:"Headlights are required from sunset to sunrise and when conditions make it difficult to see 1,000 feet ahead."},
{c:"safe",t:"tf",q:"True or False: It is legal to drive at night using only your parking lights.",a:false,
 e:"It is illegal to drive at night or in bad weather with only parking lights on."},
{c:"safe",t:"mc",q:"In fog, dust, or smoke you should use:",
 o:["High beam headlights","Low beam headlights","Parking lights only","Hazard lights while moving at normal speed"],a:1,
 e:"Use low beams in fog — high beam light reflects back, causing glare and making it harder to see."},
{c:"safe",t:"mc",q:"To reduce headlight glare from oncoming vehicles at night, you should look:",
 o:["Directly at their headlights","A little to the right, watching the road edge or fog line","At your dashboard","At the center line"],a:1,
 e:"Look a little to the right of oncoming lights and watch the road edge or fog line to avoid being blinded."},
{c:"safe",t:"mc",q:"If your vehicle begins to hydroplane, the best response is to:",
 o:["Brake hard","Slow down (ease off the gas)","Speed up to regain grip","Turn sharply toward the shoulder"],a:1,
 e:"Tires hydroplane over wet roads and steering/stopping can be lost. Slow down when roads are wet; avoid cruise control."},
{c:"safe",t:"yn",q:"Should you use cruise control on wet or icy roads?",a:false,
 e:"Do not use cruise control in wet or snowy/icy conditions."},
{c:"safe",t:"mc",q:"If your vehicle begins to skid, you should:",
 o:["Brake hard immediately","Stay off the brakes and steer in the direction you want the vehicle to go","Shift to park","Accelerate out of it"],a:1,
 e:"Stay off the brakes, steer in the direction you want to go, then correct steering left and right until you regain control."},
{c:"safe",t:"mc",q:"Bridges and shaded areas are dangerous in cold weather because they:",
 o:["Are narrower","Freeze first and may be icy when the rest of the road is clear","Have less traction paint","Attract wildlife"],a:1,
 e:"A bridge or shaded area freezes first and may be icy when the rest of the road is free of ice."},
{c:"safe",t:"tf",q:"True or False: Roads are often most slippery when the temperature is near freezing rather than well below it.",a:true,
 e:"The road is likely most slippery when the temperature is near the freezing point rather than below freezing."},
{c:"safe",t:"mc",q:"After driving through deep water, you should:",
 o:["Speed up to dry the engine","Gently apply the brakes while driving slowly until they respond","Pump the accelerator","Shift to neutral and coast"],a:1,
 e:"If brakes get wet, gently apply them while driving slowly until they begin to respond again."},
{c:"safe",t:"mc",q:"If a front tire blows out:",
 o:["Brake hard and pull over fast","Grip the wheel firmly, slow down gradually, and pull off the road","Accelerate to stabilize","Shift to neutral immediately"],a:1,
 e:"Grip the steering wheel firmly, slow down gradually, and pull off the road. A front blowout pulls strongly to one side."},
{c:"safe",t:"multi",q:"Your brakes fail. Which actions does the manual recommend? Select ALL that apply:",
 o:["Pump the brakes to build pressure","Shift to a lower gear","Slowly apply the parking brake","Turn off the ignition while moving"],a:[0,1,2],
 e:"Pump the brakes, shift to a lower gear, slowly apply the parking brake, warn others with horn or lights, and ease onto the shoulder."},
{c:"safe",t:"mc",q:"If your accelerator sticks, you should shift to:",
 o:["Park","Neutral, using an open palm","Reverse","A higher gear"],a:1,
 e:"Shift to neutral using an open palm (to avoid grabbing another gear), steer smoothly while braking, and pull off when safe."},
{c:"safe",t:"mc",q:"An oncoming vehicle drifts into your lane. You should:",
 o:["Pull into the opposing lane to dodge it","Pull right as far as possible, slow down, and warn with horn or lights","Stop in your lane","Speed past on the left"],a:1,
 e:"Never pull into the opposing lane — the driver may swerve back. Steering to the shoulder or ditch is safer than a head-on collision."},
{c:"safe",t:"mc",q:"If you drift off the pavement onto the shoulder, you should:",
 o:["Steer sharply back onto the road","Brake hard","Slow down, grip the wheel, and turn back only enough to return gently","Accelerate back on"],a:2,
 e:"Don't panic or brake hard. Slow down, keep a straight course, and turn the wheels just enough to get back on the road."},
{c:"safe",t:"mc",q:"A person on horseback raises a hand as you approach. This means:",
 o:["They want directions","The animal is frightened — stop unless stopping would cause a collision","You may pass quickly","They are turning left"],a:1,
 e:"A raised hand means the animal is frightened. Stop your vehicle, and do not use your horn or make loud noises near the animal."},
{c:"safe",t:"mc",q:"If you hit and injure a domestic animal and cannot locate the owner, you must:",
 o:["Continue on your way","Report the incident to local law enforcement","Take the animal with you","Leave a note on the road"],a:1,
 e:"Stop, make a reasonable effort to check injuries, notify the owner — or report to local law enforcement if the owner can't be found."},
{c:"safe",t:"mc",q:"Safety belts in Oregon are required for:",
 o:["Drivers only","Front-seat occupants only","All drivers and passengers in all available seating positions","Only children under 16"],a:2,
 e:"Safety belt use is mandatory for all drivers and passengers in all available seating positions."},
{c:"safe",t:"mc",q:"Children must ride in an approved child safety seat until they are 8 years old or at least:",
 o:["4 feet tall","4 feet 9 inches tall","5 feet tall","80 pounds"],a:1,
 e:"Child passengers must be restrained in approved child seats until age 8 or at least 4'9\" and the adult belt fits correctly. Infants ride rear-facing until age two."},
{c:"safe",t:"tf",q:"True or False: Infants must ride rear-facing until they reach two years of age.",a:true,
 e:"Oregon law requires infants to ride rear-facing until they reach two years of age."},
{c:"safe",t:"mc",q:"When approaching any stopped vehicle with flashing lights on a multi-lane road, you must:",
 o:["Stop behind it","Change lanes away from it, or slow at least 5 mph below the limit","Honk and pass","Maintain speed but move within your lane"],a:1,
 e:"Move over a lane so you are not next to the stopped vehicle, or slow down at least 5 mph under the posted limit. Give as much room as safely possible."},
{c:"safe",t:"mc",q:"When an emergency vehicle approaches with lights or siren, you must:",
 o:["Speed up and get out of the area","Drive as close as safely possible to the right side of the road and stop (not in an intersection)","Stop exactly where you are","Pull to the left median"],a:1,
 e:"Pull right and stop, never in an intersection. Stay stopped until it passes, then stay at least 500 feet behind it."},
{c:"safe",t:"fib",q:"After an emergency vehicle passes, you must stay at least ____ feet behind it.",a:["500","500 feet","five hundred"],
 e:"You must stay at least 500 feet behind an emergency vehicle responding with lights or siren."},
{c:"safe",t:"mc",q:"You've just started through an intersection when an ambulance approaches from behind with its siren on. You should:",
 o:["Stop in the intersection and let it go around","Pull to the right within the intersection and stop","Drive through the intersection, then pull right and stop","Speed up to outrun it"],a:2,
 e:"Manual sample question: do not stop in an intersection — continue through it, then pull to the right and stop."},
{c:"safe",t:"multi",q:"During a police stop, you should... select ALL that apply:",
 o:["Pull as far right as safely possible, stop, and turn off the engine","Keep your hands on the steering wheel","Get out and walk toward the officer","Turn on the interior light if it's dark"],a:[0,1,3],
 e:"Stay in your vehicle unless requested to get out. Limit movements, keep hands visible, and turn on the interior light at night."},
{c:"safe",t:"mc",q:"When backing up, the best practice is to:",
 o:["Rely on your mirrors","Turn your body and head to the right and look through the rear window","Open the door and look down","Use the backup camera only"],a:1,
 e:"Mirrors do not give a full view. Turn your body and head to the right, look through the rear window, glance to both sides, and back slowly."},
{c:"safe",t:"mc",q:"If a driver behind you is tailgating and there's a right lane available, you should:",
 o:["Brake hard to warn them","Move over to the right","Speed up substantially","Turn on hazard lights"],a:1,
 e:"Move right if possible, or slowly reduce speed to encourage passing. Never brake hard — you could be hit from behind."},
{c:"safe",t:"mc",q:"It is safest to drive within your lane positioned:",
 o:["Close to the center line","In the center of your lane","Close to the fog line","Wherever traffic is lightest"],a:1,
 e:"In general it is safest to drive in the center of your lane, leaving room to move left or right to avoid problems."},
{c:"safe",t:"mc",q:"Which is a sign of possible brake loss on a large truck going downhill?",
 o:["Frequent lane changes","Smoking wheels or high speed","Hazard lights on","Engine braking sounds"],a:1,
 e:"Smoking wheels or high speed can signal brake loss. Leave more space and do not pass."},
{c:"safe",t:"mc",q:"Sometimes the best way to avoid a collision is to speed up. When?",
 o:["Never — always brake","When another vehicle is about to hit you from the side or behind and there's room ahead","When traffic is merging","When an animal crosses ahead"],a:1,
 e:"Speeding up can help when a vehicle is about to hit you from the side or behind and there is room ahead to escape."},
{c:"safe",t:"multi",q:"Which are good fuel-saving techniques? Select ALL that apply:",
 o:["Drive steadily and avoid exceeding speed limits","Avoid rapid starts and sudden stops","Combine errands into a single trip","Idle the engine to warm it for 10 minutes"],a:[0,1,2],
 e:"Drive steadily, avoid rapid starts/stops and unnecessary idling, combine errands, and maintain your vehicle."},

// ============ IMPAIRED & DISTRACTED ============
{c:"impaired",t:"mc",q:"Oregon's Open Container law:",
 o:["Does not apply to anyone over 21","Requires any open bottles or containers of alcohol to be in the trunk","Allows only passengers to have open containers","Applies only on freeways"],a:1,
 e:"Manual sample question: an open (seal-broken) container is illegal in the vehicle on any road — open containers belong in the trunk."},
{c:"impaired",t:"mc",q:"You are driving and receive a text on your cell phone. What do you do?",
 o:["Read and respond to the text","Ignore the text until you stop in a safe parking area","Slow down and respond with one eye on the road","Respond only at red lights"],a:1,
 e:"Manual sample question: ignore the text until you are stopped in a safe parking area."},
{c:"impaired",t:"fib",q:"Oregon law presumes you are impaired at a blood alcohol concentration of ____ percent or more.",a:["0.08",".08","0.08%","point zero eight"],
 e:"At 0.08% BAC Oregon law presumes impairment — but you can be arrested for DUII even with a lower BAC."},
{c:"impaired",t:"mc",q:"Under Oregon's zero tolerance law, drivers under 21 fail a breath test with a BAC of:",
 o:["0.08% or more","0.04% or more","0.02% or more","Any amount of alcohol"],a:3,
 e:"If you are under 21, you fail the test with any amount of blood alcohol. Oregon has a zero tolerance law."},
{c:"impaired",t:"mc",q:"Oregon's Implied Consent law means:",
 o:["You consent to vehicle searches at any time","By driving, you have agreed to take a breath, blood, or urine test when asked by police","You must carry an organ donor card","You agree to appear in court for any citation"],a:1,
 e:"By driving a motor vehicle you've agreed to testing when asked. Refusing can bring a fine and/or suspension of driving privileges."},
{c:"impaired",t:"yn",q:"Can you be arrested for DUII with a BAC below 0.08%?",a:true,
 e:"Yes. 0.08% creates a presumption, but you can still be arrested if alcohol, cannabis, or other drugs affect your ability to drive."},
{c:"impaired",t:"tf",q:"True or False: Oregon's DUII law applies to prescription and over-the-counter medications that impair your driving.",a:true,
 e:"DUII applies to any substance that impairs your mental or physical ability to drive — including legal medications."},
{c:"impaired",t:"mc",q:"For drivers under 18, using a cell phone or mobile device while driving is:",
 o:["Allowed hands-free only","Allowed for navigation","Illegal — even hands-free","Allowed when stopped in traffic"],a:2,
 e:"It is illegal for drivers under 18 to use a cell phone or other mobile electronic device at all while operating a vehicle."},
{c:"impaired",t:"mc",q:"Drivers 18 or older may use a cell phone while driving only:",
 o:["When holding it below the window","With a hands-free accessory requiring minimal finger use to activate","At speeds under 25 mph","For calls, never texts"],a:1,
 e:"Drivers 18+ must use a hands-free accessory that requires only minimal use of a finger to activate or deactivate."},
{c:"impaired",t:"mc",q:"Playing your car's sound system so it can be heard ____ feet away is illegal.",
 o:["25","50","100","200"],a:1,
 e:"It is illegal to play audio loud enough to be heard 50 feet from your vehicle — you must be able to hear horns and sirens."},
{c:"impaired",t:"multi",q:"Which of these are illegal while driving in Oregon? Select ALL that apply:",
 o:["Having a TV or video display visible to the driver","Holding a pet in your lap","A driver under 18 using a hands-free phone","Talking with a passenger"],a:[0,1,2],
 e:"Video displays visible to the driver are illegal, don't hold a person/pet/package in your lap, and under-18 drivers may not use devices at all. Talking with passengers is legal (and can help you stay alert)."},
{c:"impaired",t:"mc",q:"If you encounter an aggressive 'road rage' driver, you should:",
 o:["Match their speed to keep distance","Stay out of the way and do not challenge them","Brake-check them","Gesture at them to back off"],a:1,
 e:"Stay out of the way. Do not challenge aggressive drivers by going faster or trying to out-drive them."},
{c:"impaired",t:"multi",q:"Which are warning signs you may be falling asleep at the wheel? Select ALL that apply:",
 o:["A lot of yawning and head nodding","Heavy eyelids or blurred vision","Not staying in your lane","Increased alertness"],a:[0,1,2],
 e:"Yawning, head nodding, heavy eyelids, blurred vision, and drifting out of your lane all mean it's time to stop and rest."},
{c:"impaired",t:"mc",q:"Which helps fight drowsiness on a long drive?",
 o:["Pushing through to your destination","Stopping in a safe place to rest or take a brisk walk","Driving faster to finish sooner","Turning up the heater"],a:1,
 e:"Never push through. Stop and rest, take a walk, drink water, talk with a passenger, or switch drivers."},
{c:"impaired",t:"yn",q:"May anyone under 18 ride in the bed of a pickup on a public road?",a:false,
 e:"Oregon law prohibits anyone under 18 from riding on the hood, fender, running board, or other external part of a vehicle, including a pickup bed."},
{c:"impaired",t:"mc",q:"Carrying a dog in a pickup bed is legal only if:",
 o:["The tailgate is up","The dog is protected by a framework, carrier, or other device to keep it from falling","The dog is leashed to the bumper","The speed stays under 35 mph"],a:1,
 e:"A dog may ride on an external part only if protected by a framework, carrier, or other device preventing a fall. Never hold an animal in your lap while driving."},
{c:"impaired",t:"mc",q:"Alcohol combined with marijuana:",
 o:["Cancels each other's effects","Can further reduce a person's ability to drive safely","Only matters for drivers under 21","Is legal if BAC stays under 0.08%"],a:1,
 e:"Using alcohol and marijuana together can reduce a person's ability to drive safely. The safest choice is not to drive after using any impairing substance."},

// ============ LICENSING, INSURANCE, COLLISIONS ============
{c:"license",t:"mc",q:"The Oregon Class C knowledge test has 35 questions. How many must you answer correctly to pass?",
 o:["25","28","30","33"],a:1,
 e:"You must answer 28 of the 35 multiple-choice questions correctly (80%) to pass."},
{c:"license",t:"fib",q:"You must be at least ____ years old to apply for an Oregon instruction permit.",a:["15","fifteen"],
 e:"You must be at least 15 to apply for an instruction permit and at least 16 to apply for a license."},
{c:"license",t:"mc",q:"If you are under 18 and applying for a driver license, you must have held an instruction permit for at least:",
 o:["3 months","6 months","12 months","30 days"],a:1,
 e:"Under-18 applicants must have held a permit for at least 6 months (out-of-state permits count)."},
{c:"license",t:"mc",q:"An under-18 applicant without an approved traffic safety course needs how many hours of supervised driving?",
 o:["25","50","100","150"],a:2,
 e:"100 hours of supervised driving — or 50 hours plus an ODOT-approved traffic safety education course."},
{c:"license",t:"mc",q:"Supervised driving experience only counts if the supervisor is at least 21 and has had valid driving privileges for at least:",
 o:["1 year","2 years","3 years","5 years"],a:2,
 e:"The supervisor must be at least 21 years old with valid driving privileges for at least 3 years."},
{c:"license",t:"mc",q:"A Class C non-commercial license covers vehicles of not more than:",
 o:["10,000 pounds","16,000 pounds","26,000 pounds","33,000 pounds"],a:2,
 e:"Class C covers passenger cars, mopeds, autocycles, vans, or pickups of not more than 26,000 pounds not requiring CDL or motorcycle endorsements."},
{c:"license",t:"mc",q:"Oregon's minimum bodily injury liability insurance for one person per collision is:",
 o:["$15,000","$20,000","$25,000","$50,000"],a:2,
 e:"Minimums: $25,000 per person / $50,000 per collision bodily injury; $20,000 property damage; $15,000 PIP; $25,000/$50,000 uninsured motorist."},
{c:"license",t:"fib",q:"Oregon's minimum property damage liability coverage is $____ per collision.",a:["20,000","20000","$20,000","twenty thousand"],
 e:"$20,000 per collision for damage to the property of others is the required minimum."},
{c:"license",t:"mc",q:"You must file a DMV collision report (Form 735-32) within:",
 o:["24 hours","48 hours","72 hours","10 days"],a:2,
 e:"File within 72 hours when damage exceeds $2,500, a vehicle is towed due to damage, or there is injury or death. A police report does not replace it."},
{c:"license",t:"fib",q:"A collision must be reported to DMV if damage to any vehicle is over $____.",a:["2,500","2500","$2,500","twenty five hundred"],
 e:"The reporting threshold is $2,500 in damage to a vehicle or other property (or any injury/death, or any vehicle towed due to damage)."},
{c:"license",t:"multi",q:"After a collision you must... select ALL that apply:",
 o:["Stop, and move drivable vehicles out of travel lanes if no injuries","Give reasonable assistance to injured persons","Exchange name, address, license, plate and insurance information","Leave if the damage looks minor"],a:[0,1,2],
 e:"Stop, help the injured, and exchange information. If someone is killed or unconscious, remain at the scene until police arrive."},
{c:"license",t:"mc",q:"If you hit an unoccupied parked vehicle and cannot find the owner, you must:",
 o:["Drive on — it's not reportable","Leave a note with your name, address, and a brief description of what happened","Call a tow truck","Wait 30 minutes then leave"],a:1,
 e:"Try to find the owner; if you can't, leave a note with your name and address and a brief description of what happened."},
{c:"license",t:"multi",q:"Which can cause you to LOSE your driving privileges? Select ALL that apply:",
 o:["Driving under the influence of intoxicants","Failing to report a vehicle collision","Driving uninsured","Receiving a single parking ticket"],a:[0,1,2],
 e:"DUII, failing to report a collision, driving uninsured, too many traffic convictions, and unpaid court fines can all cost you your privileges."},
{c:"license",t:"yn",q:"Does a police report replace your requirement to file a collision report with DMV?",a:false,
 e:"No — a police report does not replace your requirement to file your own report with DMV."},
{c:"license",t:"mc",q:"If you fail the drive test, you may retake it:",
 o:["The same day","The next business day at the earliest","After 7 days","After 30 days"],a:1,
 e:"If you fail the drive test, you must wait until the next business day to retake it. (A failed knowledge test may be retaken the same day at an office, resources permitting.)"},
{c:"license",t:"mc",q:"If you are caught cheating on a DMV knowledge test:",
 o:["You get a warning","You fail and cannot test again for 90 days","You pay a $50 fine","You must test online next time"],a:1,
 e:"Cheating (talking, notes, cell phone, devices, or having someone test for you) means you fail and cannot test again for 90 days."},
{c:"license",t:"mc",q:"Who is allowed in the vehicle during a DMV drive test?",
 o:["You, the examiner, and one parent","Only you and the examiner","You, the examiner, and a translator","Anyone with a license"],a:1,
 e:"Only you and the examiner. Translators, family, friends, and pets are not allowed."},
{c:"license",t:"multi",q:"Which items must be in working order for your drive-test vehicle to pass the equipment check? Select ALL that apply:",
 o:["Turn signals front and back, brake lights, and horn","Seatbelts and non-bald tires","Passenger door that opens/closes from inside and outside","Premium sound system"],a:[0,1,2],
 e:"The examiner checks signals, brake lights, horn, doors, seats, seatbelts, tires, muffler, registration, mirrors, and an unobstructed view."},
{c:"license",t:"mc",q:"DMV may waive your drive test if:",
 o:["You completed an ODOT-approved driver education course within the past two years","You have a valid learner's permit","You are over 25","You passed the knowledge test with 100%"],a:0,
 e:"The drive test may be waived for new residents surrendering a valid out-of-state license, or with proof of an ODOT-approved driver ed course within two years."},
{c:"license",t:"tf",q:"True or False: You must show valid proof of insurance for your vehicle before taking the drive test.",a:true,
 e:"Bring current registration and valid proof of insurance, or you will have to reschedule the drive test."},
{c:"license",t:"mc",q:"On the online knowledge test, if you are under 18:",
 o:["You cannot test online","A proctor over 21 must supervise the test","A parent must co-sign electronically","You must use a tablet"],a:1,
 e:"Under-18 online test takers need a proctor over 21. A proctor can supervise only two tests in 24 hours."},
{c:"license",t:"mc",q:"How many total times may you take the knowledge test online before you must test at a DMV office?",
 o:["Two","Three","Four","Unlimited"],a:2,
 e:"You may take the online test four times total (max two attempts per 24 hours). After four attempts, you must test at an office."},

// ============ SHARING THE ROAD ============
{c:"sharing",t:"mc",q:"A person on a bicycle rides in front of you in your lane. You're going 45 mph and there's a broken yellow center line. You:",
 o:["Can pass left if you leave enough distance to prevent contact if the rider falls into your lane","Should honk and tell them to move over","Cannot pass a bicycle at any time","Must follow at 10 feet until they exit"],a:0,
 e:"Manual sample question: over 35 mph you may pass a bicycle in your lane only leaving enough distance to prevent contact if the rider were to fall."},
{c:"sharing",t:"mc",q:"A large vehicle ahead swings left but has its right turn signal on. You are also turning right. You should:",
 o:["Stay beside it on the right","Wait until the large vehicle completes its turn before you turn","Squeeze between the vehicle and the curb","Honk and pass on the left"],a:1,
 e:"Manual sample question: large vehicles swing wide to turn. Never cut in between a large vehicle and the curb — wait for it to finish."},
{c:"sharing",t:"mc",q:"When must you stop for a pedestrian in a crosswalk?",
 o:["Only in marked crosswalks","When they are in your lane, the lane next to yours (including a bike lane), or the lane you are turning into","Only when a crossing guard is present","Only at signals"],a:1,
 e:"Stop and remain stopped when the pedestrian is in your lane, an adjacent lane (including a bike lane), or the lane you're turning into."},
{c:"sharing",t:"tf",q:"True or False: There is a crosswalk at every intersection, even if it is not marked with painted lines.",a:true,
 e:"Every intersection has a crosswalk, marked or unmarked. An unmarked crosswalk is at least six feet wide and exists even without a sidewalk or shoulder."},
{c:"sharing",t:"mc",q:"Passing a vehicle stopped at a crosswalk is:",
 o:["Allowed if you slow down","Against the law — the driver may be waiting for a pedestrian","Allowed on multi-lane roads","Allowed if you can see the crosswalk is empty"],a:1,
 e:"Do not pass a vehicle stopped at a crosswalk — it is against the law. The driver may be waiting for a pedestrian you can't see."},
{c:"sharing",t:"mc",q:"Turning at a signal-controlled intersection, you may begin your turn when a crossing pedestrian is at least:",
 o:["Out of the entire road","Six feet or more from the lane you are turning into","Past the center line","On the sidewalk"],a:1,
 e:"At a signalized intersection the pedestrian must be six feet or more from your target lane. Without a signal, they must be past your lane plus the next lane."},
{c:"sharing",t:"mc",q:"A pedestrian carrying a white cane or using a guide dog is crossing. You must:",
 o:["Yield until they clear your lane","Remain stopped until they have crossed the entire road, even on a green light","Pass slowly behind them","Honk gently to guide them"],a:1,
 e:"Stop and remain stopped until a blind or deaf-blind pedestrian has crossed the entire road, even if your light turns green."},
{c:"sharing",t:"yn",q:"A pedestrian is in a crosswalk on the other side of a safety island. Are you required to stop?",a:false,
 e:"You are not required to stop if the pedestrian is in a crosswalk on the other side of a safety island."},
{c:"sharing",t:"mc",q:"When crossing a sidewalk to leave a parking lot or driveway, you must:",
 o:["Proceed slowly with horn ready","Stop before reaching the sidewalk and yield to pedestrians and people on bicycles","Yield only to pedestrians","Have the right of way over sidewalk users"],a:1,
 e:"Stop before the sidewalk and yield to pedestrians and people riding bicycles."},
{c:"sharing",t:"tf",q:"True or False: You may move into a bicycle lane to prepare for a right turn.",a:false,
 e:"Do not move into or travel in a bike lane in preparation for a turn. You may cross a bike lane when turning, yielding to riders first."},
{c:"sharing",t:"mc",q:"Before turning right on a green light at an intersection with a bike box, you must:",
 o:["Stop inside the green box first","Signal and yield to people riding bicycles on your right","Never turn right at these intersections","Merge into the bike lane early"],a:1,
 e:"Stop behind the bike box on red (no right turns on red there). On green, signal and yield to people riding bicycles on the right."},
{c:"sharing",t:"yn",q:"May you turn right on a red light at an intersection with a bike box?",a:false,
 e:"No right turns are allowed on red at bike-box intersections. Stop behind the box, not in it."},
{c:"sharing",t:"mc",q:"It is against the law to share a lane with:",
 o:["A bicycle","A person riding a motorcycle or moped","A transit bus","Another car when parking"],a:1,
 e:"You may not share a lane with a motorcycle or moped. When passing, you must give them a full lane."},
{c:"sharing",t:"mc",q:"An oncoming motorcycle has its turn signal on. Before turning across its path you should:",
 o:["Turn quickly before it arrives","Make sure the rider is actually slowing to turn — signals may not cancel automatically","Flash your lights and turn","Assume it will turn"],a:1,
 e:"Motorcycle signals may not self-cancel; the rider may have forgotten it. Be sure they're actually turning — it's safest to wait until they pass."},
{c:"sharing",t:"mc",q:"When following a motorcycle, you should:",
 o:["Follow closer since they're smaller","Allow MORE following distance than for a car","Use your high beams so they see you","Match their lane position"],a:1,
 e:"Allow more distance behind motorcycles — weather, wind and road surfaces affect riders more, and they can stop quickly."},
{c:"sharing",t:"mc",q:"If you can't see a truck driver in their side mirror:",
 o:["They can still see you on camera","The driver can't see you — you're in their blind spot","You're at a safe distance","You should honk"],a:1,
 e:"Large vehicles have big blind spots on both sides and deep ones behind. If you can't see the driver in the mirror, they can't see you."},
{c:"sharing",t:"mc",q:"Compared with cars at the same speed, large trucks take about how much distance to stop?",
 o:["The same","Twice as much","Three times as much","Half as much"],a:2,
 e:"Large vehicles take about three times the distance to stop as smaller vehicles at the same speed."},
{c:"sharing",t:"mc",q:"When a large vehicle is backing up and blocking the street, you should:",
 o:["Cross close behind it while it's slow","Never cross behind it — wait until it finishes","Honk so the driver stops","Drive around its front quickly"],a:1,
 e:"Never cross behind a large vehicle that is preparing to back up or is backing — the driver cannot see you."},
{c:"sharing",t:"mc",q:"You see a pilot vehicle (escorting an oversize load) in oncoming traffic. You should:",
 o:["Stop completely","Reduce speed and move as far right as possible while staying in your lane","Pull onto the shoulder and wait","Flash your high beams"],a:1,
 e:"Reduce speed and position your vehicle as far right as possible in your lane. Increase following distance if you're behind one."},
{c:"sharing",t:"mc",q:"When water is on the road and a large truck is spraying, you should:",
 o:["Draft close behind for visibility","Stay as far from the truck as you can while staying in your lane","Pass immediately on the right","Turn on high beams"],a:1,
 e:"Truck spray seriously reduces vision. Keep as far away as you can while staying in your lane."},
{c:"sharing",t:"mc",q:"Operators of motorized wheelchairs and mobility devices in bike lanes:",
 o:["Must move for cars","Must be yielded to just as you would a person riding a bicycle","Are prohibited from bike lanes","Have no right of way"],a:1,
 e:"Motorized wheelchairs, scooters, and personal assistive mobility devices may use bike lanes and paths — yield to them as you would a bicycle."},
{c:"sharing",t:"mc",q:"A load extending 4 feet or more beyond the rear of a vehicle must display:",
 o:["A white flag","A red flag at least 12 inches square (or a red light in limited visibility)","An orange triangle","Nothing if under 6 feet"],a:1,
 e:"A red flag at least 12 inches square is required, replaced by a red light visible for 500 feet in limited visibility conditions."},
{c:"sharing",t:"yn",q:"May passengers legally ride in an ordinary utility trailer being towed?",a:false,
 e:"Passengers may not ride in trailers, except commercial bus trailers, independently-steered trailers, or properly equipped fifth-wheel trailers."},
{c:"sharing",t:"mc",q:"Before opening your car door when parked on a street with light rail tracks, you should:",
 o:["Open it quickly","Check for approaching streetcars, trains and cyclists first","Turn on hazards","Honk twice"],a:1,
 e:"Always check for approaching streetcars or trains (and riders) before opening vehicle doors."},
{c:"sharing",t:"tf",q:"True or False: You may turn in front of a streetcar traveling in the same direction in the adjacent lane if it is stopped.",a:false,
 e:"Never turn in front of a streetcar or train traveling in the same direction from an adjacent lane, even if it is stopped."}
];
